name: Tests

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      - id: gotest
        env:
          FOO: bar
          BAR: baz
        run: go test ./...
      - run: |
          echo "Output for FOO_OUT: ${{ steps.gotest.outputs.FOO_OUT }}"
          if [[ '${{ steps.gotest.outputs.FOO_OUT }}' != 'bartest' ]]; then exit 1; fi
          echo "Output for bar_out: ${{ steps.gotest.outputs.bar_out }}"
          if [[ '${{ steps.gotest.outputs.bar_out }}' != 'baztest' ]]; then exit 1; fi
